title: RTK1-V6 + RTK3-REMAIN
author: Mạnh Tài
url: http://manhtai.github.io/rtk
description: "Remembering the Kanji: rtk.manhtai.com"

permalink: /:title/

exclude:
 - README.md

gems:
  - jekyll-redirect-from
